config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :orders
  resources :clients
  resources :areas
  root 'orders#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ApplicationRecord
  has_many :orders

  def not_delivered
    self.orders.select{|x| x.delivered? == false}
  end
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :order, optional: true
  belongs_to :width_measure
  belongs_to :height_measure
  resourcify
end

app/models/client.rb
class Client < ApplicationRecord
  validates :name, :presence => true
  has_many :orders
  resourcify

end

app/models/height_measure.rb
class HeightMeasure < ApplicationRecord
  has_many :articles
end

app/models/order.rb
class Order < ApplicationRecord
  validates :client, :presence => true
  validates :direction, :presence => true
  belongs_to :client
  belongs_to :area

  has_many :articles, dependent: :destroy, inverse_of: :order
  accepts_nested_attributes_for :articles, allow_destroy: true,
   reject_if: :reject_posts

  resourcify

  def reject_posts(attributes)
    attributes['quantity'].blank? && attributes['width'].blank? && attributes['height'].blank?
  end

  def done?
    self.articles.select{|x| x.done == 1 }.count == self.articles.count
  end

  def delivered?
    self.articles.select{|x| x.delivered == 1 }.count == self.articles.count
  end

  def invoiced?
    self.articles.select{|x| x.invoiced == 1 }.count == self.articles.count
  end

end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/width_measure.rb
class WidthMeasure < ApplicationRecord
  has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  include Pundit
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = "No estas autorizado a realizar esta acción."
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController

  def index
    @areas = Area.all
    authorize Area
  end

  def show
    @area = Area.find(params[:id])
  end

  def new
    @area = Area.new
    authorize @area
  end

  def create
    @area = Area.new(area_params)
    authorize @area

    if @area.save
      flash[:notice] = "Area creada correctamente"
      redirect_to areas_path
    else
      flash[:alert] = "#{@area.errors.count} error no permitio crear este areae: "
      @area.errors.full_messages.each do |msg|
        flash[:alert] << "#{msg}"
        flash[:alert] << ", " unless @area.errors.full_messages.last == msg
      end
      render 'new'
    end
  end

  def edit
    @area = Area.find(params[:id])
    authorize @area
  end

  def update
    @area = Area.find(params[:id])
    authorize @area

    if @area.update(area_params)
      flash[:notice] = "Area actualizada correctamente"
      redirect_to areas_path
    else
      flash[:alert] = "#{@order.errors.count} error no permitio actualizar esta areae: "
      @order.errors.full_messages.each do |msg|
        flash[:alert] << "#{msg}"
        flash[:alert] << ", " unless @order.errors.full_messages.last == msg
      end
      render 'edit'
    end
  end

  def destroy
    @area = Area.find(params[:id])
    authorize @area
    @area.destroy

    redirect_to areas_path
  end


  private

  def area_params
    params.require(:area).permit(:name)
  end

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController

  def index
    @clients = Client.all
    authorize Client
  end

  def show
    @client = Client.find(params[:id])
    authorize @client
  end

  def new
    @client = Client.new
    authorize @client
  end

  def create
    @client = Client.new(client_params)
    authorize @client

    if @client.save
      flash[:notice] = "Cliente creado correctamente"
      redirect_to clients_path
    else
      flash[:alert] = "#{@client.errors.count} error no permitio crear este cliente: "
      @client.errors.full_messages.each do |msg|
        flash[:alert] << "#{msg}"
        flash[:alert] << ", " unless @client.errors.full_messages.last == msg
      end
      render 'new'
    end
  end

  def edit
    @client = Client.find(params[:id])
    authorize @client
  end

  def update
    @client = Client.find(params[:id])
    authorize @client

    if @client.update(client_params)
      flash[:notice] = "Pedido actualizado correctamente"
      redirect_to clients_path
    else
      flash[:alert] = "#{@order.errors.count} error no permitio actualizar este cliente: "
      @order.errors.full_messages.each do |msg|
        flash[:alert] << "#{msg}"
        flash[:alert] << ", " unless @order.errors.full_messages.last == msg
      end
      render 'edit'
    end
  end

  def destroy
    @client = Client.find(params[:id])
    authorize @client
    @client.destroy

    redirect_to clients_path
  end


  private

  def client_params
    params.require(:client).permit(:name)
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def index
    @orders = Order.all
    authorize Order
  end

  def show
    @order = Order.find(params[:id])
    authorize @order
  end

  def new
    @order = Order.new
    @order.articles.build
    authorize @order
  end

  def create
    @order = Order.new(order_params)
    authorize @order

    if @order.save
      flash[:notice] = "Pedido creado correctamente"
      redirect_to root_path
    else
      flash[:alert] = "#{@order.errors.count} errors prohibited this order from being saved: "
      @order.errors.full_messages.each do |msg|
        flash[:alert] << "#{msg}"
        flash[:alert] << ", " unless @order.errors.full_messages.last == msg
      end
      render 'new'
    end
  end

  def edit
    @order = Order.find(params[:id])
    @order.articles.build
    authorize @order
  end

  def update
    @order = Order.find(params[:id])
    authorize @order

    if @order.update(order_params)
      flash[:notice] = "Pedido actualizado correctamente"
      redirect_to root_path
    else
      #If i cant update, i render again the edit view
      flash[:alert] = "#{@order.errors.count} errores no permitieron actualizar este pedido: "
      @order.errors.full_messages.each do |msg|
        flash[:alert] << "#{msg}"
        flash[:alert] << ", " unless @order.errors.full_messages.last == msg
      end
      render 'edit'
    end
  end

  def destroy
    @order = Order.find(params[:id])
    authorize @order
    @order.destroy

    redirect_to orders_path
  end

  private

  def order_params
    params.require(:order).permit(:direction, :client_id, :area_id,
      articles_attributes: [:id, :_destroy, :order_id, :quantity, :width, :height,
         :long, :description, :done, :delivered, :invoiced, :width_measure_id, :height_measure_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/areas/_form.html.erb
<%= simple_form_for @area do |form| %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="form-group">
      <%= form.input :name, label: "Nombre", class: "form-control text-center" %>
      <br/>
      <%= form.button :submit, class: "btn btn-success" %>
    </div>
  </div>
</div>
<% end %>

app/views/areas/edit.html.erb
<%= render "form" %>

app/views/areas/index.html.erb
<h1 class"h1">Zonas</h1>

<br/><br/>

<div>
  <div>
      <table class="table">
        <thead class="thead-dark">
          <tr>
            <th scope="col">#</th>
            <th scope="col">Nombre</th>
            <th scope="col">Pedidos a Entregar</th>
          </tr>
        </thead>
        <tbody>
          <% if @areas.present? %>
          <% x=0 %>
            <% @areas.each do |area| %>
              <tr>
                <th scope="row"><%= x+=1 %></th>
                <td>
                  <%= link_to area.name, area %>
                </td>
                <td> <%= area.not_delivered.count %> </td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    <div>
      <% if policy(Client).new? %>
        <%= link_to 'Nueva Zona', new_area_path, class: "btn btn-outline-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/areas/new.html.erb
<%= render 'form' %>

app/views/areas/show.html.erb
<div class="row justify-content-center">
  <h1> <%= @area.name %> </h1>
</div>
<hr>
<div class="row justify-content-center">
  <h2>Pedidos:</h2>
</div>


<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Cliente</th>
      <th scope="col">Fecha</th>
      <th scope="col">Direccion</th>
      <th scope="col">Procesado</th>
      <th scope="col">Entregado</th>
      <th scope="col">Facturado</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% if @area.not_delivered.present? %>
    <% x=0 %>
      <% @area.not_delivered.each do |order| %>
        <tr>
          <th scope="row"><%= x+=1 %></th>

          <td> <%= order.client.name %> </td>
          <td> <%= order.created_at.to_date.to_formatted_s(:iso8601) %> </td>
          <td> <%= order.direction %> </td>

          <td><%= check_box "order", "done?", {:checked => order.done?, :disabled => true}%></td>
          <td><%= check_box "order", "delivered?", {:checked => order.delivered?, :disabled => true}%></td>
          <td><%= check_box "order", "invoiced?", {:checked => order.invoiced?, :disabled => true}%></td>

          <td> <%= link_to "Ver", order_path(order) %> </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<div class="row justify-content-center">
  <% if policy(@area).edit? %>
    <%= link_to "Editar", edit_area_path(@area), class: "btn btn-primary" %>
  <% end %>
  &nbsp;
  <% if policy(@area).edit? %>
    <%= link_to 'Eliminar',area_path(@area), method: :delete, class: "btn btn-danger",
                                data: { confirm: 'Are you sure?' } %>
  <% end %>
</div>

app/views/clients/_form.html.erb
<%= simple_form_for @client do |form| %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="form-group">
      <%= form.input :name, label: "Nombre", class: "form-control text-center" %>
      <br/>
      <%= form.button :submit, class: "btn btn-success" %>
    </div>
  </div>
</div>
<% end %>

app/views/clients/index.html.erb
<h1 class"h1r">Clientes</h1>

<br/><br/>

<div>
  <div>
      <table class="table">
        <thead class="thead-dark">
          <tr>
            <th scope="col">#</th>
            <th scope="col">Nombre</th>
            <th scope="col">Cantidad de Pedidos</th>
          </tr>
        </thead>
        <tbody>
          <% if @clients.present? %>
          <% x=0 %>
            <% @clients.each do |client| %>
              <tr>
                <th scope="row"><%= x+=1 %></th>
                <td>
                  <%= link_to client.name, client %>
                </td>
                <td> <%= client.orders.count %> </td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    <div>
      <% if policy(Client).new? %>
        <%= link_to 'Nuevo Cliente', new_client_path, class: "btn btn-outline-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/clients/show.html.erb
<div class="row justify-content-center">
  <h1> <%= @client.name %> </h1>
</div>
<hr>
<div class="row justify-content-center">
  <h2>Pedidos:</h2>
</div>


<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Fecha</th>
      <th scope="col">Direccion</th>
      <th scope="col">Procesado</th>
      <th scope="col">Entregado</th>
      <th scope="col">Facturado</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% if @client.orders.present? %>
    <% x=0 %>
      <% @client.orders.each do |order| %>
        <tr>
          <th scope="row"><%= x+=1 %></th>

          <td> <%= order.created_at.to_date.to_formatted_s(:iso8601) %> </td>
          <td> <%= order.direction %> </td>

          <td><%= check_box "order", "done?", {:checked => order.done?, :disabled => true}%></td>
          <td><%= check_box "order", "delivered?", {:checked => order.delivered?, :disabled => true}%></td>
          <td><%= check_box "order", "invoiced?", {:checked => order.invoiced?, :disabled => true}%></td>

          <td> <%= link_to "Ver", order_path(order) %> </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<div class="row justify-content-center">
  <% if policy(@client).edit? %>
    <%= link_to "Editar", edit_client_path(@client), class: "btn btn-primary" %>
  <% end %>
  &nbsp;
  <% if policy(@client).edit? %>
    <%= link_to 'Eliminar',client_path(@client), method: :delete, class: "btn btn-danger",
                                data: { confirm: 'Are you sure?' } %>
  <% end %>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">MaderNorte</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <%= render "layouts/navigation_links" %>
    </ul>
    <ul class="navbar-nav my-2 my-lg-0">
      <%= render 'devise/menu/login_items' %>
      <%= render 'devise/menu/registration_items' %>
    </ul>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<% if user_signed_in? %>
  <li class="nav-item">
    <%= link_to "Pedididos", orders_path, class: "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to "Clientes", clients_path, class: "nav-link" %>
  </li>
  <% if policy(Area).index?%>
    <li class="nav-item">
      <%= link_to "Reparto", areas_path, class: "nav-link" %>
    </li>
  <% end %>
  <% if current_user.has_role? :admin %>
    <%= link_to "Admin", rails_admin_path, class: "nav-link" %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Madernorte</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>

    <main role="main">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/orders/_article_fields.html.erb
<tr class="nested-fields">
  <td> <%= link_to_remove_association "Eliminar articulo", f, class: "btn btn-danger" %> </td>
  <td> <%= f.input :quantity, label: false %> </td>
  <td> <%= f.input :width, label: false %> </td>
  <td> <%= f.association :width_measure, label: false %> </td>
  <td> <%= f.input :height, label: false %> </td>
  <td> <%= f.association :height_measure, label: false %> </td>
  <td> <%= f.input :long, label: false %> </td>
  <td> <%= f.input :description, label: false %> </td>
  <td> <%= f.input :done, as: :boolean, label: false %> </td>
  <td> <%= f.input :delivered, as: :boolean, label: false %> </td>
  <td>
    <% if (current_user.has_role?(:admin) || current_user.has_role?(:vendor))  %>
      <%= f.input :invoiced, as: :boolean, label: false %>
    <% end %>
  </td>
</tr>

app/views/orders/_form.html.erb
<%= simple_form_for @order do |form| %>

<div>
  <div>
    <div>
      <% if (current_user.has_role?(:admin) || current_user.has_role?(:vendor))  %>
        <%= form.association :client, label: "Cliente", class: "" %>
        <hr>
        <%= form.input :direction, label: "Direccion", class: "" %>
        <%= form.association :area, label: "Zona", class: "" %>
      <% elsif current_user.has_role? :worker %>
        <h1> Pedido N°: <%= @order.id %> </h1>
        <h2> Fecha: <%= @order.created_at.to_date.to_formatted_s(:iso8601) %> </h2>
        <h3> Cliente: <%= link_to @order.client.name, client_path(@order.client) %> </h3>
        <h3> Direccion: <%= @order.direction %> </h3>
        <hr>
      <% end %>

      <table class="table table-striped">
        <thead>
          <tr>
            <th></th>
            <th>Piezas</th>
            <th>Ancho</th>
            <th class="measure"></th>
            <th class="measure">Alto</th>
            <th class="measure"></th>
            <th class="measure-long">Largo</th>
            <th>Descripcion</th>
            <th>Procesado</th>
            <th>Entregado</th>
            <th>Facturado</th>
          </tr>
        </thead>

        <tbody class="articles">
          <%= form.simple_fields_for :articles do |form_builder| %>
            <%= render 'article_fields', f:  form_builder %>
          <% end %>
        </tbody>

      </table>

      <br/>

      <div class="">
        <%= form.button :submit, class: "btn btn-success"  %>
        <%= link_to_add_association "Agregar Articulo", form, :articles, class: "btn btn-primary",
        data: { association_insertion_node: ".articles", association_insertion_method: :append } %>
      </div>
    </div>
  </div>
</div>

<% end %>

app/views/orders/index.html.erb
<div class="row justify-content-center">
  <h1 class"h1">Pedidos</h1>
</div>

<div>
  <div>
      <table class="table">
        <thead class="thead-dark">
          <tr>
            <th scope="col">#</th>
            <th scope="col">Cliente</th>
            <th scope="col">Direccion</th>
            <th scope="col">Fecha</th>
            <th scope="col">Procesado</th>
            <th scope="col">Entregado</th>
            <th scope="col">Facturado</th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
          <% if @orders.present? %>
          <% x=0 %>
            <% @orders.each do |order| %>
              <tr>
                <th scope="row"><%= x+=1 %></th>

                <td> <%= link_to order.client.name, order.client %> </td>
                <td> <%= order.direction %> </td>
                <td> <%= order.created_at.to_date.to_formatted_s(:iso8601) %> </td>

                <td><%= check_box "order", "done?", {:checked => order.done?, :disabled => true}%></td>
                <td><%= check_box "order", "delivered?", {:checked => order.delivered?, :disabled => true}%></td>
                <td><%= check_box "order", "invoiced?", {:checked => order.invoiced?, :disabled => true}%></td>

                <td>
                  <%= link_to "Ver", order_path(order) %>
                </td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    <div>
      <div class="row justify-content-center">
        <% if policy(Order).new? %>
          <%= link_to 'Nuevo Pedido', new_order_path, class: "btn btn-outline-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/orders/show.html.erb
<h1> Pedido N°: <%= @order.id %> </h1>
<h2> Fecha: <%= @order.created_at.to_date.to_formatted_s(:iso8601) %> </h2>
<h3> Cliente: <%= link_to @order.client.name, client_path(@order.client) %> </h3>
<h3> Direccion: <%= @order.direction %> </h3>
<hr>
<div class="row justify-content-center">
  <h3> Articulos: </h3>
</div>


<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Piezas</th>
      <th scope="col">Ancho</th>
      <th></th>
      <th scope="col">Alto</th>
      <th></th>
      <th scope="col">Largo</th>
      <th scope="col">Descripcion</th>
      <th scope="col">Procesado</th>
      <th scope="col">Entregado</th>
      <th scope="col">Facturado</th>
    </tr>
  </thead>
  <tbody>
    <% if @order.articles.present? %>
      <% x=0 %>
      <% @order.articles.each do |article| %>
        <tr>
          <th scope="row"><%= x+=1 %></th>

          <td> <%= sprintf("%g", article.quantity) %> </td>
          <td> <%= sprintf("%g", article.width) %> </td>
          <td> <%= article.width_measure.name %> </td>
          <td> <%= sprintf("%g", article.height) %> </td>
          <td> <%= article.height_measure.name %> </td>
          <td> <%= sprintf("%g", article.long) %> </td>
          <td> <%= article.description %> </td>

          <td><%= check_box "article", "done", {:checked => article.done?, :disabled => true} %></td>
          <td><%= check_box "article", "delivered", {:checked => article.delivered?, :disabled => true }%></td>
          <td><%= check_box "article", "invoiced", {:checked => article.invoiced?, :disabled => true} %></td>

        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<div class="row justify-content-center">
  <% if policy(@order).edit? %>
    <%= link_to "Editar", edit_order_path(@order), class:"btn btn-primary" %>
  <% end %>
  &nbsp;
  <% if policy(@order).destroy? %>
    <%= link_to 'Eliminar', order_path(@order), class:"btn btn-danger",
        method: :delete, data: { confirm: 'Estas seguro?' } %>
  <% end %>
</div>